name: dzero
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  go_router: ^6.5.2
  flutter_riverpod: ^2.3.4
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  image_picker: ^0.8.7+2
  font_awesome_flutter: ^10.4.0
  http: ^0.13.5
  cloudinary_public: ^0.13.0
  firebase_database: ^10.1.1
  flutter_dotenv: ^5.0.2
  awesome_circular_chart: ^1.0.0
  animate_do: ^3.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/presets/
    - .env